pipeline {
    agent any
    environment {
        IMAGE_NAME = 'flask-cicd'
    }
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/Fayaz-2/flask-jenkins-ansible.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('app') {
                    script {
                        sh "docker build -t $IMAGE_NAME ."
                    }
                }
            }
        }
        stage('Push Image (Optional if using Docker Hub)') {
            steps {
                echo 'Skipping image push...'
            }
        }
        stage('Deploy using Ansible') {
            steps {
                sh 'ansible-playbook ansible/deploy.yml'
            }
        }
    }
}

