- name: Deploy Flask Docker App on EC2
  hosts: ec2
  become: true
  tasks:
    - name: Stop existing container
      shell: docker rm -f flask-cicd || true

    - name: Pull and run docker image
      shell: docker run -d --name flask-app -p 5000:5000 fayaz3/flaskapp
