- hosts: localhost
  become: true
  tasks:
    - name: Stop old container if running
      shell: docker stop flask-app || true

    - name: Remove old container if exists
      shell: docker rm flask-app || true

    - name: Pull latest image
      shell: docker pull fayaz3/flask-app:latest

    - name: Run new container
      shell: docker run -d --name flask-app -p 5000:5000 fayaz3/flask-app:latest
